version: '3'
services:
  db:
    image: postgres:14.2-bullseye
    restart: always
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: andromeda
      POSTGRES_PASSWORD: andromedagoodstar
    tmpfs:
      - /var/lib/postgresql/data