version: '3'
services:
  db:
    image: postgres:14.2-bullseye
    #    image: postgres:13.4-bullseye
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DATABASE: app_db
      POSTGRES_USER: andromeda
      POSTGRES_PASSWORD: andromedagoodstar
    # Uncomment this if you want to persist the data.
    volumes:
      - "../../../data/database/pgdata:/var/lib/postgresql/data"
